### ISSUE TITLE
Missing .csv and .vot files in downloads

### ISSUE THREAD

**Issue by esabol** [Binary-rEvolution/LMXBwebcat#12]
Would you add (at least) a `.csv` version of the FITS file to the downloads directory (similar to how you've done HMXBwebcat)? Thanks!

Ping: @ffortin-sci-edu

**Comment by ffortin-sci-edu** [comment]
Hello,
Yes this is planned, the LMXBwebcat should operate the exact same way as the HMXBwebcat. For now the website is in "beta" as the paper is currently under review, the remaining features will be integrated by the time it gets accepted. I'll add the .csv and .vot today, and try to also implement a symbolic link to the latest version as requested for HMXBwebcat.
Best,
Francis

**Comment by esabol** [comment]
OK, thank you, @ffortin-sci-edu ! Good to know. I think we will probably wait until the paper is out of review before making it available in our database system. Please reach out to us when that happens.

**Comment by esabol** [comment]
Resolved. Thank you!
